---
# input related
:contents_dir: 'contents/*.chg'
:static:
  :dir: 'contents/static/'
:theme:
  :dir: 'theme/'
  :template_path: 'template/'
:custom_theme:
  :dir: 'custom/'
  :template_path: 'template/'
  :eyecatch_template_path: 'eyecatch_template/'

# output related (output has fixed dir structure, ./images, ./css, ./javascript
:output_dir: 'out/'
:rss_filename: 'index.rdf'
:path_of:
  :css: 'css/'
  :javascript: 'javascript/'
  :images: 'images/'
# url related
:home_url: 'http://localhost:8080/'
:site_logo: "logo-copy.png"

# contents related
:title: 'example site'
:subtitle: 'blog by CLoveR'
:categories:
- :category_name: null 
  :dirname: ""
  :eyecatch: "logo-copy.png"
- :category_name: 'category1'
  :file_name: 'categ1'
  :dirname: "category1/"
  :eyecatch: "category1_eyecatch.jpg"
- :category_name: 'category2'
  :file_name: 'categ2'
  :dirname: 'category2/'
  :eyecatch: "category2_eyecatch.jpg"
# site owner related
:twitter: '@example'
:googleanalysis: 'UA-xxxxxx-xx'
